### ISSUE TITLE
JS linting fails on 2 gulpfiles

### ISSUE THREAD

**Issue by lkopacz** [acquia-pso/cog#108]
Specifically: 

- Missing space before function parentheses (14:31 compile-sass.js)
- Expected indentation errors  (15:13 lint-css.js)
- Expected indentation errors  (16:17 lint-css.js)
- Expected indentation errors  (17:17 lint-css.js)
- Expected indentation errors  (18:13 lint-css.js)
- Expected indentation errors  (29:13 lint-css.js)
- Expected indentation errors  (30:17 lint-css.js)
- Expected indentation errors  (31:17 lint-css.js)
- Expected indentation errors  (32:17 lint-css.js)
- Expected indentation errors  (33:13 lint-css.js)
- Missing semicolon (35:10 lint-css.js)

CONFIRMED: This appears to happen after the drush cog command is run and creates a subtheme from the STARTERKIT bundle.

**Comment by sarahjean** [comment]
Fixed with 1.8
