### ISSUE TITLE
Update COG readme to specify the most appropriate version of node to use.

### ISSUE THREAD

**Issue by arknoll** [acquia-pso/cog#109]
Documentation currently says 4.4.4. This is apparently wrong and we can run in the 6.x version

**Comment by sarahjean** [comment]
@aellison is working on this on https://github.com/acquia-pso/cog/pull/110

**Comment by lkopacz** [comment]
@aellison created a new PR for this in https://github.com/acquia-pso/cog/pull/114

**Comment by sarahjean** [comment]
Merged
