### ISSUE TITLE
Why was plumber removed?

### ISSUE THREAD

**Issue by Fidelix** [acquia-pso/cog#117]
https://github.com/acquia-pso/cog/commit/141f8421a62c744c478d8b566966afea78ac5829

It's annoying having to re-run gulp when there are sass errors.
If the concern is that the process no longer returns an error at the exit signal that can easily be fixed with a
```
.on('error', $.sass.logError)
```
right before autoprefixer.

**Comment by aellison** [comment]
Plumber was added back to most of the tasks after we fixed a bug. PRs are welcome if you would like to add it back to the `compile-sass` task.

**Comment by aellison** [comment]
Plumber added back to the compile-sass task in latest release.
