### ISSUE TITLE
Subtheme names with spaces not preserved during generation

### ISSUE THREAD

**Issue by danepowell** [acquia-pso/cog#136]
If you try to generate a subtheme with a space in the name following the instructions, it comes out weird...

> drush cog "Cog Foo"

... produces a theme whose machine name is correctly set as `cog_foo`, but the human name in `cog_foo.info.yml` is set as `Cog cog_foo` instead of `Cog Foo`.

**Comment by sarahjean** [comment]
@danepowell can you take a look at this https://github.com/acquia-pso/cog/pull/139, should make it so if you give drush a string you get the exact same thing set as the human friendly name. If you do `drush cog cog_foo` you get cog_foo, if you do `drush cog "Cog Foo"` you get Cog Foo.

**Comment by danepowell** [comment]
#139 works great, thanks.

Also, I can't resist:
![Cog Foo](https://i.imgflip.com/22ksyn.jpg)

**Comment by sarahjean** [comment]
LOL
