### ISSUE TITLE
minify:css gulp task running in parallel to compile:sass

### ISSUE THREAD

**Issue by wu-edward** [acquia-pso/cog#137]
I ran npm run build for the first time on a subtheme and noticed this:
`[10:16:07] Starting 'compile:sass'...
[10:16:07] Starting 'minify:css'...
[10:16:07] Starting 'compile:styleguide'...
[10:16:07] Finished 'minify:css' after 252 ms
Style guide build completed successfully!
[10:16:07] Finished 'compile:styleguide' after 460 ms
[10:16:08] Finished 'compile:sass' after 1.88 s`

The minify:css task completed before SASS compiling. I verified that the minified CSS file was not generated.

When I updated a .scss file and ran the build again, the minified CSS file was generated, but did not reflect the latest SASS update.

.libraries.yml by default points to the unminified CSS, so it's not noticeable in browser unless the library is updated to point to the minified file.

**Comment by sarahjean** [comment]
@wu-edward Can you please test out https://github.com/acquia-pso/cog/pull/138 and see if it resolves this.

**Comment by wu-edward** [comment]
@sarahjean Yup, lgtm.

**Comment by sarahjean** [comment]
Fixed
