### ISSUE TITLE
Rework drush command to support drush 9

### ISSUE THREAD

**Issue by sarahjean** [acquia-pso/cog#145]
The current command is not compatible with drush 9 at all. There are some docs on creating new commands or porting legacy commands here: http://docs.drush.org/en/master/commands/

**Comment by sarahjean** [comment]
Short summary  to expand on the issue:
drush 9 no longer supports discovery of drush commands from inside themes, only modules, and doesn't use the .drush.inc files anymore. For discussion on support in themes see https://github.com/drush-ops/drush/pull/3089

It seems like a good way to go would be to set up a 'cog_tools' type module to house the command and possible other more module appropriate features in the future.

We can leave the .drush.inc file in place for drush 8, but drupal 8.5+ will need drush 9 so we need to have an alternative soon.

**Comment by aweingarten** [comment]
Also see:  https://github.com/acquia/blt/issues/2729

**Comment by ctgreybeard** [comment]
I just ran into this when I decided to try cog out. I got a good recommendation for it ...

I have a new site running Drupal 8.5.3 with drush 9.2.3 and, as described, drush 9 doesn't know about cog. As I'm just starting to play with this can I help? I'm not a drupal or drush expert but I do know my way around a system pretty well. This is just a personal project so I don't mind messing with it.

**Comment by sarahjean** [comment]
@ctgreybeard We've actually got something started regarding this: https://github.com/acquia-pso/cog_tools

It is a bit different in a few ways to the task in this theme.
- It's provided by a module
- It's a generator that uses templates, rather than copying and changing text from a built out subtheme
- The theme it generates is a starterkit that is based on classy, rather than a cog base theme
- There are no more templates, and the only custom classes are there for sidebar styling
- Not all the features are fleshed out and a few bits are borked due to twig template conversion, but are probably going to be moved out anyway.

Testing would be much appreciated!

There's a readme that has getting started instructions, but enabling the module and running `drush gen cog` is the main bit.

**Comment by ctgreybeard** [comment]
Thanks! I'll jump over there ...
