### ISSUE TITLE
Conditional field logic breaks webforms

### ISSUE THREAD

**Issue by sarahjean** [acquia-pso/cog#157]
See bug report on D.O. here https://www.drupal.org/project/cog/issues/2966701

**Comment by alzz** [comment]
Webform conditional fields needs "js-form-item" & "js-form-item-FIELD" in order to work.
Basically I have updated the template with the latest version of the one that implements the Classy theme.

Pull request [https://github.com/acquia-pso/cog/pull/159](https://github.com/acquia-pso/cog/pull/159)
