### ISSUE TITLE
Accessibility issue aria-labelledby referenced id

### ISSUE THREAD

**Issue by batcapu** [acquia-pso/cog#158]
Hi,
I had to modify the template themes/contrib/cog/templates/block/block--system-menu-block.html.twig
Because it was generating an issue in wave
![image](https://user-images.githubusercontent.com/28634061/42423641-9f048972-82cb-11e8-97ee-0b7ca61b5130.png)

When I inspected the code I noticed there was an extra '-menu' which broke the relationship between the aria-labelledby and the id

My solution was to remove a piece of code from the template and the problem was resolved.
` ~ '-menu'`
![image](https://user-images.githubusercontent.com/28634061/42423662-0342e8a2-82cc-11e8-8084-657b311734c4.png)

**Comment by mikemadison13** [comment]
I ran into a similar issue and worked through it with @sarahjean. This approach seems to fix the issue for me using Lighthouse audits in Chrome.

**Comment by mikemadison13** [comment]
may be related to https://www.drupal.org/node/2723961
