### ISSUE TITLE
What is the included Fontawesome used for specifically?

### ISSUE THREAD

**Issue by hmartens** [acquia-pso/cog#167]
Under libraries.yml there is a fontawesome cdn line. What is this used for? if I remove it, will something break? If I want to update it to the latest 5.0.0, will it break anything that comes standard with Cog?

Also, the CDN link is not the default fontawesome cdn server, is there a reason for this?

Thank you

**Comment by sarahjean** [comment]
@hmartens The fontawesome line, and the google font, are both in there as starter/examples of loading assets from external URLs.  It won't break anything to take it out or change it to point to the official free or paid CDN.
