### ISSUE TITLE
Gulp JS errors during BLT build

### ISSUE THREAD

**Issue by jenter** [acquia-pso/cog#21]
Whenever I run `blt frontend:build` I get a whole bunch of these: /docroot/themes/custom/hamilton/gulpfile.js
  65:1  error  Use the function form of 'use strict'  strict

**Comment by jenter** [comment]
@aellison can you take a look at this when reviewing the BLT integration task.

**Comment by jenter** [comment]
@aellison a client brought this up yesterday with Sean Clark, can you review and we can discuss today.

**Comment by aellison** [comment]
@jenter Looking into this.

**Comment by aellison** [comment]
@jenter There was a change in core's `.eslintrc` in Drupal 8.2. The `'use strict'` declaration needs to be done inside of functions.

**Comment by aellison** [comment]
Fix in #26
