### ISSUE TITLE
As a COG user I'd like to know which standard mixins to use

### ISSUE THREAD

**Issue by aweingarten** [acquia-pso/cog#37]
As a styler working with COG I need to user SASS mixins.  I would like guidance for which standard mixin libraries I should use so that my skills can easily transfer from one cog project to another.

For example if I want to create CSS3 animations I would expect to use a mixin to create vendor specific effects.

**Comment by skippednote** [comment]
@aweingarten  I'm not completely clear with respect to the question but you can create custom mixins and place them in the `_config.scss` file. Apart from that, we ship multiple Sass libraries like breakpoint, typey, susy, etc which expose mixins for various needs.

As far as mixins for vendor prefixes are concerned, you don't need to worry about those as it is handled at build time by `autoprefixer`.

**Comment by jenter** [comment]
@aweingarten since we are not utilizing Cog as a place for our preferences with mixins, we will close this and will have documentation on including libraries.
