### ISSUE TITLE
Require components module

### ISSUE THREAD

**Issue by aweingarten** [acquia-pso/cog#45]
There should be a composer.json that includes
https://www.drupal.org/project/components

That should also be added as a requirement to the theme

**Comment by jenter** [comment]
@aweingarten this is an option for project-specific tasks, so we are leaving this out for now. 
We can review options for documenting this in our next round.

**Comment by aweingarten** [comment]
@jenter this should be used on any project?   I can't imagine doing a new D8 build without styleguide driven development?

**Comment by jenter** [comment]
@aweingarten sorry, wasn't saying we aren't going to use it.. just not in the base build. 
I will reopen so we can include with optional framework.

**Comment by aellison** [comment]
@aweingarten I think this should be an issue for BLT. Not sure we want it to be a hard requirement for Cog.
