### ISSUE TITLE
Create default directory for custom js, add example script

### ISSUE THREAD

**Issue by grasmash** [acquia-pso/cog#58]
There should be an established convention for where to place custom JS. Ideally, this directory would contain a shell of a custom script. The shell would properly use D8's JS framework and be added in the libraries.yml file already.

**Comment by jenter** [comment]
TODO // Create JS Readme in JS/ folder and add snippet.

**Comment by jenter** [comment]
Completed with PR https://github.com/acquia-pso/cog/pull/60
