### ISSUE TITLE
Add class to front-page

### ISSUE THREAD

**Issue by aweingarten** [acquia-pso/cog#70]
Ideally there should be a class on the front-page body to help targeting for css.

Might also be a good idea to add some twig variables or functions that are globally acessible.  e.g. http://drupal.stackexchange.com/questions/136122/check-if-its-the-front-page-in-the-template

**Comment by skippednote** [comment]
We are already adding a `frontpage` class on the body tag. 
**ref:** https://github.com/acquia-pso/cog/blob/8.x-1.x/STARTERKIT/STARTERKIT.theme#L38
