### ISSUE TITLE
How to change out Susy Grid for Bootstrap Grid

### ISSUE THREAD

**Issue by captaindav** [acquia-pso/cog#72]
Are there specific steps that can be taken to change out the Susy Grid for the Bootstrap grid?

Are there any plans to implement the Bootstrap grid as an option in Cog (essentially make the grid "pluggable")?

Thanks for you help, I am very impressed with Cog so far!

**Comment by jenter** [comment]
@captaindav thank you, I can create some documentation before EOD to share. It's a relatively quick process since we use it minimally.

**Comment by captaindav** [comment]
@jenter Would it make sense to have a separate starter kit for the Bootstrap grid, similar to how the Bootstrap theme (https://www.drupal.org/project/bootstrap) has less and sass starter kits?  The bootstrap startkit may also need to override some of the cog theme templates too, not sure how that should work?

If you think adding a Bootstrap specific starter kit makes sense, I will work on getting a pull request submitted.

**Comment by jenter** [comment]
@captaindav here's a PR to display initial removal of grid: https://github.com/acquia-pso/cog/pull/89

**Comment by captaindav** [comment]
@jenter  Thanks for identifying the code that needs to be modified in order to  implement a different grid in #89 . I will proceed with creating/testing a Bootstrap grid based Cog theme, and once that is working, create a PR for a Bootstrap Starter Kit.

I think the main things that need to be accomplished are: 

1) Add a drush command for the new starter kit, e.g. drush cog-bootstrap "MyTheme"  
2) Remove susy from packages.json. 
3) _containers.scss: remove Susy mixin and create desired container.  
4) _panels.scss and _sidebar.scss: replace Susy mixins with grid declarations.
5) _config.scss: remove $susy variable.
6) styles.scss: remove susy @import.
7) gulpfile.js: remove susy reference from list of front end dependencies. 
8) Create libraries in the starter kit for bootstrap js and css.

**Comment by digisimp** [comment]
Looks like CSS Grids are going to be the way to go. Singularity has shutdown and even though Susy has come out with version 3, they recommend going to CSS Grids (http://oddbird.net/2017/06/28/susy3/) and they were also thinking about shutting it down.

**Comment by sarahjean** [comment]
We have an open issue around that: https://github.com/acquia-pso/cog/issues/116 but probably still need to take into a account fallbacks for older browsers.

**Comment by sarahjean** [comment]
This isn't too bad an approach for the original request: https://dev.acquia.com/blog/bootstrapping-blt-use-the-bootstrap-3-theme-with-blt/15/12/2016/17376

Given the css grid direction and that this was only a support request, gonna go ahead and close.
