### ISSUE TITLE
npm run install-tools does not work

### ISSUE THREAD

**Issue by vbouchet31** [acquia-pso/cog#81]
I am completely new with all this frontend tools so I may have missed something.

The [documentation](https://github.com/acquia-pso/cog/blob/8.x-1.x/STARTERKIT/_readme/setup-full.md#local-development) mentions about `npm run install-tools` but it is failing.

> $ npm run install-tools
> npm ERR! Darwin 15.6.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "install-tools"
> npm ERR! node v4.4.1
> npm ERR! npm  v2.14.20

> npm ERR! missing script: install-tools
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>

I cant see any script or mention in any "executable" files.

Is the documentation outdated? Is this "install-tools" a default command from npm which is not working on my local?

**Comment by jenter** [comment]
@vbouchet31 this was resolved by PR https://github.com/acquia-pso/cog/pull/82
We will do a Drupal.org release by end of week.
