### ISSUE TITLE
Views Fields & Filter Criteria Ajax Errors

### ISSUE THREAD

**Issue by nickrussell** [acquia-pso/cog#84]
When editing a view, if I click on any of the fields or filter criteria links to edit a field or filters settings, an ajax error is encountered and the field settings form is unable to display.

**The Result of Click**
![sharing_frame_window](https://cloud.githubusercontent.com/assets/428815/24519311/8f15bb9a-1539-11e7-861b-2d6a89bb3125.jpg)

**The Javascript Console Error After Click**
![sharing_frame_window](https://cloud.githubusercontent.com/assets/428815/24519329/9e5c9984-1539-11e7-80ee-74bc5e7f4fce.jpg)

The issue appears to be a result of javascript failing, resulting in an inability to complete the ajax request for the settings form.

Affects version 8.x-1.6

**Comment by sarahjean** [comment]
@nickrussell What leads you to believe that Cog is the source of the issue? From the screenshot it looks like you are using Seven in the views ui on the admin side.

**Comment by aellison** [comment]
Cog was never intended to be an admin theme. Closing.
