### ISSUE TITLE
Unable to alter $variables['attributes']['class']

### ISSUE THREAD

**Issue by dakkusingh** [acquia-pso/cog#86]
It seem there is an issue with how Attributes are getting processed in COG. For example, the following code does not output any additional classes. It works fine with other themes.

```
function mymodule_preprocess_block(&$variables) {
  if (empty($variables['content']['#block_content'])) {
    return;
  }

  $variables['attributes']['class'][] = Html::cleanCssIdentifier('col-1');
}
```

**Comment by jenter** [comment]
Closing after testing confirmed fix in PR #87
