### ISSUE TITLE
Add fix:css task that matches stylelint linting

### ISSUE THREAD

**Issue by sarahjean** [acquia-pso/cog#99]
Implementation notes:
Suggestions found in https://css-tricks.com/stylelint/

https://github.com/ben-eb/perfectionist
https://github.com/morishitter/stylefmt
or 
https://github.com/csscomb/csscomb.js

**Comment by danepowell** [comment]
I just tried stylefmt and it worked like a charm. Surprisingly easy to use. There were just a few errors it couldn't fix automatically.

**Comment by danepowell** [comment]
This should be doable with the gulp-stylefmt plugin, but the problem I've run into is that stylefmt only takes a single file as argument. It can't take an entire directory or wildcard path like the CSS lint targets do.

There's an open issue for gulp-stylefmt on this: https://github.com/morishitter/gulp-stylefmt/issues/6

**Comment by sarahjean** [comment]
@danepowell Huh, yeah that'll be a bit of a problem with all the partials we tend to have floating around...
